### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/lgmm-html-Hello#1]
# Review

Buen trabajo Luis.

Podrías obtrener una mejor visualización de las imágenes en la galería si le agregaras estas clases `class="img img-fluid"`.

Mira el resultado cuando se las aplico a las tres primeras.

![Captura desde 2023-07-25 17-11-01](https://github.com/4GeeksAcademy/lgmm-html-Hello/assets/45291267/84188bdf-c622-479b-bb8e-6ef0ca2b3f4b)

![Captura desde 2023-07-25 17-16-00](https://github.com/4GeeksAcademy/lgmm-html-Hello/assets/45291267/b2b53ce8-f454-4eb2-8520-65300ab7269b)

### También...

podrías agregar  `class="container"` a tu `div` principal 

![Captura desde 2023-07-25 17-14-59](https://github.com/4GeeksAcademy/lgmm-html-Hello/assets/45291267/d461c31d-dd52-4004-a6db-cd137e92c387)

**Comment by lgmedina23** [comment]
estuve batallando bastante con el codigo para dar exactamente con eso de las imagines pero no logre conseguirlo, bueno saber que si existe. hice todos los cambios y lo agrege git. 

Me quedo la duda del "container" en este caso particular de que me servia meter todo en un contenedor??

**Comment by hchocobar** [comment]
Mañana, en clases, te muestro los cambios que podrías hacer, vale?

**Comment by lgmedina23** [comment]
vale vale!
